name: Build Limbo_Tensor APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 31
          ndk: false  # No need for NDK if just using precompiled .so

      - name: Grant Gradle execute permission
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: limbo_tensor-debug
          path: app/build/outputs/**/*.apk
