name: Build & Sign Limbo_Tensor

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 31

      - name: Grant Gradle Execute Permission
        run: chmod +x gradlew

      # 1. Build Debug & Release APK
      - name: Build Debug & Release
        run: |
          ./gradlew assembleDebug --stacktrace
          ./gradlew assembleRelease --stacktrace

      # 2. Decode Keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore

      # 3. Sign Release APK
      - name: Sign Release APK
        run: |
          RELEASE_APK=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore release.keystore \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            "$RELEASE_APK" ${{ secrets.KEY_ALIAS }}

      # 4. Upload Artifacts
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: limbo_tensor-apks
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/release/*.apk
